openapi: 3.0.0
info:
  title: pacemaker.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/auth/signup:
    post:
      summary: 회원가입
      operationId: post-v1-auth-signup
      responses:
        '201':
          description: 회원가입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    $ref: '#/components/schemas/LoginResponse'
        '400':
          description: request body 잘못됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: string
        '409':
          description: 이메일 중복됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: string
      tags:
        - 인증
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./ssutudy-api.v1.yaml#/components/schemas/SignUpRequest
        description: ''
      description: 로그인 할 때 사용
  /v1/auth/signin:
    post:
      summary: 로그인
      operationId: post-v1-auth-signin
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    $ref: '#/components/schemas/LoginResponse'
        '400':
          description: request body 잘못됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: string
        '404':
          description: 아이디 또는 비밀번호 잘못됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
        description: 회원가입 할 때 사용
      tags:
        - 인증
  /v1/studies:
    get:
      summary: 스터디 목록 조회
      tags:
        - 스터디
      responses:
        '200':
          description: 조회 성공한 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/StudyOverview'
        '401':
          description: 액세스 토큰이 없거나 만료된 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: string
      operationId: get-v1-studies
      parameters:
        - schema:
            type: string
          in: query
          name: tag
          description: |-
            태그

            LANGUAGE 외국어

            IT IT/컴퓨터

            NATIONAL_EXAM 고시/공무원

            CERTIFICATE 자격증

            ENTRANCE_EXAM 입시

            EMPLOYMENT 취업

            OTHER 기타
          enum:
            - LANGUAGE
            - IT
            - NATIONAL_EXAM
            - CERTIFICATE
            - ENTRANCE_EXAM
            - EMPLOYMENT
            - OTHER
      security:
        - Authorization: []
      description: ' 스터디룸 찾기 페이지에서 사용'
    post:
      summary: 스터디 생성
      operationId: post-v1-studies
      responses:
        '201':
          description: 스터디 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    $ref: '#/components/schemas/StudyOverview'
        '401':
          description: 액서스 토큰이 없거나 만료된 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: string
      description: ''
      security:
        - Authorization: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudyRequest'
  /v1/studies/recent:
    get:
      summary: 최근 스터디 목록 조회
      tags:
        - 스터디
      responses:
        '200':
          description: 조회 성공한 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/StudyOverview'
        '401':
          description: 액세스 토큰이 없거나 만료된 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: string
      operationId: get-v1-recent-studies
      parameters: []
      security:
        - Authorization: []
      description: |-
        스터디룸 찾기 페이지에서
         
         `따끈따끈 신상 스터디룸` 목록
  /v1/studies/recommend:
    get:
      summary: 추천 스터디 목록 조회
      tags:
        - 스터디
      responses:
        '200':
          description: 조회 성공한 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/StudyOverview'
        '401':
          description: 액세스 토큰이 없거나 만료된 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: string
      operationId: get-v1-recommend-studies
      parameters:
        - schema:
            type: string
          in: query
      security:
        - Authorization: []
      description: |2-







         스터디룸 찾기 페이지에서
         
         `이 스터디룸은 어때요?` 목록
  '/v1/studies/{studyId}/questions':
    parameters:
      - schema:
          type: string
        name: studyId
        in: path
        required: true
    get:
      summary: 질문 목록 조회
      tags:
        - 질문
      responses:
        '200':
          description: 조회 성공한 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: string
        '401':
          description: 액세스 토큰이 없거나 만료된 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: api 호출 성공 여부
                  data:
                    type: string
      operationId: get-v1-studies-studyId-questions
      description: 스터디룸 질문 게시판 페이지에서 사용
      security:
        - Authorization: []
components:
  schemas:
    SignInRequest:
      title: SignInRequest
      type: object
      properties:
        email:
          type: string
          description: 이메일
          format: email
        password:
          type: string
          description: 비밀번호
      required:
        - email
        - password
    SignUpRequest:
      title: SignUpRequest
      type: object
      properties:
        email:
          type: string
          description: 이메일
        name:
          type: string
          description: 이름
        major:
          type: string
          description: 전공
        studentId:
          type: string
          description: 학번
        password:
          type: string
          description: 비밀번호
        birthday:
          type: string
          description: 생년월일
        academicStatus:
          type: string
          description: 학적상태
          enum:
            - TAKE_OFF
            - ATTENDING
      required:
        - email
        - name
        - major
        - studentId
        - password
        - birthday
        - academicStatus
    LoginResponse:
      title: LoginResponse
      type: object
      properties:
        accessToken:
          type: string
          description: 액세스 토큰
        refreshToken:
          type: string
          description: 리프레시 토큰
        user:
          $ref: '#/components/schemas/UserNameAndId'
      required:
        - accessToken
        - refreshToken
        - user
    UserNameAndId:
      title: UserNameAndId
      type: object
      properties:
        id:
          description: 사용자 id
          type: integer
        name:
          type: string
          description: 이름
      required:
        - id
        - name
    StudyOverview:
      title: StudyOverview
      type: object
      properties:
        id:
          type: integer
          description: 스터디 id
        title:
          type: string
          description: 제목
        description:
          type: string
          description: 설명
        countParticipant:
          type: integer
          description: 인원
        ranking:
          type: integer
          description: 랭킹
        tag:
          type: string
          description: |-
            태그

            LANGUAGE 외국어

            IT IT/컴퓨터

            NATIONAL_EXAM 고시/공무원

            CERTIFICATE 자격증

            ENTRANCE_EXAM 입시

            EMPLOYMENT 취업

            OTHER 기타
          enum:
            - LANGUAGE
            - IT
            - NATIONAL_EXAM
            - CERTIFICATE
            - ENTRANCE_EXAM
            - EMPLOYMENT
            - OTHER
      required:
        - id
        - title
        - description
        - countParticipant
        - ranking
        - tag
    QuestionOverview:
      title: QuestionOverview
      type: object
      properties:
        id:
          type: integer
          description: 질문 id
        title:
          type: string
          description: 질문 제목
        content:
          type: string
          description: 질문 내용
        writer:
          $ref: '#/components/schemas/UserNameAndId'
        createdAt:
          type: string
          format: date
          description: 작성자 정보
        countLike:
          type: integer
          description: 좋아요 수
        countComment:
          type: integer
          description: 댓글 수
      required:
        - id
        - title
        - content
        - writer
        - createdAt
        - countLike
        - countComment
    CreateStudyRequest:
      title: CreateStudyRequest
      type: object
      properties:
        title:
          type: string
          description: 제목
        description:
          type: string
          description: 설명
        tag:
          type: string
          description: |-
            태그

            LANGUAGE 외국어

            IT IT/컴퓨터

            NATIONAL_EXAM 고시/공무원

            CERTIFICATE 자격증

            ENTRANCE_EXAM 입시

            EMPLOYMENT 취업

            OTHER 기타
          enum:
            - LANGUAGE
            - IT
            - NATIONAL_EXAM
            - CERTIFICATE
            - ENTRANCE_EXAM
            - EMPLOYMENT
            - OTHER
      required:
        - title
        - description
        - tag
  responses: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: '`Bearer ${accessToken}` 형식으로 설정해주세요'
tags:
  - name: 인증
