openapi: 3.0.0
info:
  title: ssutudy-api
  version: '1.0'
  contact:
    email: skfk0135@gmail.com
  description: ssutudy API 스펙 문서
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
