openapi: 3.0.0
info:
  title: ssutudy-api
  version: '1.0'
  contact:
    email: skfk0135@gmail.com
  description: ssutudy API 스펙 문서
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/auth/sign-in:
    post:
      summary: 로그인
      tags:
        - 인증
        - v1
      responses:
        '200':
          description: 로그인 성공한 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: 요청 바디 형식이 잘못됐을 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 비밀번호나 아이디 값이 틀려서 로그인 실패한 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: get-v1-auth-sign-in
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
  /v1/auth/sign-up:
    post:
      summary: 회원가입
      tags:
        - 인증
        - v1
      responses:
        '201':
          description: 회원가입 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: 요청 바디 형식이 잘못됐을 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: 아이디가 중복될 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: get-v1-auth-sign-up
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
  /v1/studies:
    get:
      summary: 스터디 목록 조회
      tags:
        - 스터디
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStudiesResponse'
        '400':
          description: userId와 search 파라미터를 동시에 사용하는 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: |-
            Authorizion 헤더 형식이 잘못된 경우 (아래와 같은 형식이어야 합니다)
            `Bearer {accesstoken}`

            또는 Authorizion 헤더에 access token을 전달하지 않은 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: get-v1-studies
      description: |-
        내 스터디를 조회하고 싶다면
        /v1/studies?userId={내 아이디}

        모든 스터디를 검색하고 싶다면
        /v1/studies

        스터디를 검색하고 싶다면
        /v1/studies?search={키워드}
      parameters:
        - schema:
            type: string
          in: query
          name: userId
          description: 사용자 아이디
        - schema:
            type: string
          in: query
          name: search
          description: 검색 키워드
      security:
        - Authorization: []
    post:
      summary: 스터디 생성
      operationId: post-v1-studies
      responses:
        '201':
          description: 성공적으로 스터디 생성한 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStudyResponse'
        '400':
          description: 요청 바디 형식이 잘못된 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: |-
            Authorizion 헤더 형식이 잘못된 경우 (아래와 같은 형식이어야 합니다)
            `Bearer {accesstoken}`

            또는 Authorizion 헤더에 access token을 전달하지 않은 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: ''
      security:
        - Authorization: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewStudyRequest'
        description: ''
      tags:
        - 스터디
  '/v1/users/{users}/change-password':
    parameters:
      - schema:
          type: string
        name: users
        in: path
        required: true
    post:
      summary: 비밀번호 변경
      tags:
        - 사용자
      responses:
        '204':
          description: 비밀번호 변경 성공
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '400':
          description: 요청 바디 형식이 잘못된 경우입니다
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: |-
            Authorizion 헤더 형식이 잘못된 경우 (아래와 같은 형식이어야 합니다)
            `Bearer {accesstoken}`

            또는 Authorizion 헤더에 access token을 전달하지 않은 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 기존 비밀번호가 잘못된 경우입니다
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: get-v1-users-users-change-password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
        description: ''
      security:
        - Authorization: []
  '/v1/studies/{studyId}':
    parameters:
      - schema:
          type: string
        name: studyId
        in: path
        required: true
        description: 스터디 id
    get:
      summary: 스터디 조회
      tags:
        - 스터디
      responses:
        '200':
          description: 스터디를 성공적으로 조회한 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStudiesResponse'
        '401':
          description: |-
            Authorizion 헤더 형식이 잘못된 경우 (아래와 같은 형식이어야 합니다)
            `Bearer {accesstoken}`

            또는 Authorizion 헤더에 access token을 전달하지 않은 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 스터디가 없는 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: get-v1-studies-studyId
      security:
        - Authorization: []
      description: ''
  '/v1/studies/{studyId}/participate':
    parameters:
      - schema:
          type: string
        name: studyId
        in: path
        required: true
        description: 스터디 id
    post:
      summary: 스터디 참여
      operationId: post-v1-studies-studyId-participate
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: |-
            Authorizion 헤더 형식이 잘못된 경우 (아래와 같은 형식이어야 합니다)
            `Bearer {accesstoken}`

            또는 Authorizion 헤더에 access token을 전달하지 않은 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 스터디가 없는 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: |-
            최대 참여 인원이 다 차서
            더 이상 참여할 수 없는 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      description: ''
      security:
        - Authorization: []
      tags:
        - 스터디
    get:
      summary: 참가하고 있는 스터디인지 확인
      operationId: get-v1-studies-studyId-participate
      responses:
        '200':
          description: 성공적으로 참가하고 있는 스터디인지 확인한 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckParticipateStatusResponse'
      tags:
        - 스터디
  /v1/study-logs:
    post:
      summary: ''
      operationId: post-v1-study-logs
      responses:
        '200':
          description: OK
      tags:
        - 스터디
    get:
      summary: 공부 시간
      tags:
        - 스터디
components:
  schemas:
    SignInRequest:
      title: SignInRequest
      type: object
      properties:
        id:
          type: string
          description: 사용자 아이디
        password:
          type: string
          description: 사용자 비밀번호
      required:
        - id
        - password
    TokenResponse:
      title: TokenResponse
      type: object
      properties:
        accessToken:
          type: string
          description: access token
        user:
          $ref: '#/components/schemas/UserDetail'
      required:
        - accessToken
        - user
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        timestamp:
          type: integer
          description: 에러 발생 시간 timestamp
        status:
          description: http status code
          type: integer
        error:
          type: string
          description: http status reason phrase
        message:
          type: string
          description: 에러 메시지
        path:
          type: string
          description: 에러 발생한 api path
      required:
        - timestamp
        - status
        - error
        - message
        - path
    SignUpRequest:
      title: SignUpRequest
      type: object
      properties:
        id:
          type: string
          description: '사용자 아이디  '
        major:
          type: string
          description: 사용자 전공
        name:
          type: string
          description: 사용자 이름
        password:
          type: string
          description: 사용자 비밀번호
      required:
        - id
        - major
        - name
        - password
    StudySummary:
      title: StudySummary
      type: object
      properties:
        title:
          type: string
          description: 스터디명
        participantNumber:
          type: string
          description: 스터디 참여하고 있는 인원
        tags:
          type: array
          description: 태그 목록
          items:
            $ref: '#/components/schemas/TagItem'
        attendance:
          $ref: '#/components/schemas/AttendanceItem'
        id:
          type: integer
          description: 스터디 id
      required:
        - title
        - participantNumber
        - tags
        - attendance
        - id
    TagItem:
      title: TagItem
      type: object
      properties:
        name:
          type: string
          description: 태그 이름
      required:
        - name
    AttendanceItem:
      title: AttendanceItem
      type: object
      properties:
        beginAt:
          type: string
          description: 스터디 출석 정기적으로 시작하는 시간
        endAt:
          type: string
          description: |-
            스터디 출석 정기적으로 종료하는 시간
            이후에 출석하는 사람은 전부 지각
      required:
        - beginAt
        - endAt
    GetStudiesResponse:
      title: GetStudiesResponse
      type: object
      properties:
        studies:
          $ref: '#/components/schemas/StudySummary'
    ChangePasswordRequest:
      title: ChangePasswordRequest
      type: object
      properties:
        originalPassword:
          type: string
          description: 기존 비밀번호
        newPassword:
          type: string
          description: 새로운 비밀번호
      required:
        - originalPassword
        - newPassword
    UserDetail:
      title: UserDetail
      type: object
      properties:
        id:
          type: string
          description: 사용자 아이디
        name:
          type: string
          description: 사용자 이름
        major:
          type: string
          description: 사용자 전공
      required:
        - id
        - name
        - major
    StudyDetail:
      title: StudyDetail
      type: object
      description: ''
      properties:
        title:
          type: string
          description: 스터디명
        participantNumber:
          type: string
          description: 스터디 참여하고 있는 인원
        tags:
          type: array
          description: 태그 목록
          items:
            $ref: '#/components/schemas/TagItem'
        attendance:
          $ref: '#/components/schemas/AttendanceItem'
        id:
          type: integer
          description: 스터디 id
        paricipantLimit:
          type: integer
          description: 최대 참가 인원 수
        description:
          type: string
          description: 스테디 설명
      required:
        - title
        - participantNumber
        - tags
        - attendance
        - id
        - paricipantLimit
        - description
    GetStudyResponse:
      title: GetStudyResponse
      type: object
      properties:
        study:
          $ref: '#/components/schemas/StudyDetail'
      required:
        - study
    CheckParticipateStatusResponse:
      title: CheckParticipateStatusResponse
      type: object
      properties:
        isParticipating:
          type: boolean
          description: 스터디 참여하고 있는 지 여부
      required:
        - isParticipating
    NewStudyRequest:
      title: NewStudyRequest
      type: object
      properties:
        title:
          type: string
          description: 스터디명
        description:
          type: string
          description: 스터디 상세 설명
        attendance:
          $ref: '#/components/schemas/NewAttendanceRequest'
        participantLimit:
          type: integer
          description: 최대 참여 인원 수
        tags:
          type: array
          description: 태그 목록
          items:
            type: string
      required:
        - title
        - description
        - participantLimit
        - tags
    NewAttendanceRequest:
      title: NewAttendanceRequest
      type: object
      properties:
        beginAt:
          type: string
          description: 스터디 출석 정기적으로 시작하는 시간
          format: time
        endAt:
          type: string
          description: |-
            스터디 출석 정기적으로 종료하는 시간
            이후에 출석하는 사람은 전부 지각
          format: time
      required:
        - beginAt
        - endAt
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
tags:
  - name: 인증
  - name: v1
  - name: 스터디
  - name: 사용자
